name: helloworld
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  url_launcher: ^6.1.11

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - lib/assets/Archive DM Icon.png
    - lib/assets/Archives LM Icon.png
    - lib/assets/Arrow Divider DM.png
    - lib/assets/Arrow Divider LM.png
    - lib/assets/Banner.png
    - lib/assets/Exit DM Icon.png
    - lib/assets/Exit LM Icon.png
    - lib/assets/Home DM Icon.png
    - lib/assets/Home LM Icon.png
    - lib/assets/Moon Icon.png
    - lib/assets/PHantasya Logo DM.png
    - lib/assets/PHantasya Logo LM.png
    - lib/assets/Quiz DM Icon.png
    - lib/assets/Quiz LM Icon.png
    - lib/assets/Settings DM Icon.png
    - lib/assets/Settings LM Icon.png
    - lib/assets/Sun Icon.png
    - lib/assets/QuizDownDM.png
    - lib/assets/QuizDownLM.png
    - lib/assets/QuizUpLM.png
    - lib/assets/QuizUpDM.png
    - lib/assets/QuizScoreLM.png
    - lib/assets/QuizScoreDM.png
    - lib/assets/Balbal.png
    - lib/assets/Bakunawa.png
    - lib/assets/Tikbalang.png
    - lib/assets/WhiteLady.png
    - lib/assets/Manananggal.png
    - lib/assets/Balbal2.png
    - lib/assets/AsCat.png
    - lib/assets/EngCat.png
    - lib/assets/GGCat.png
    - lib/assets/GhoCat.png
    - lib/assets/HaliCh.png
    - lib/assets/ManCh.png
    - lib/assets/MisCat.png
    - lib/assets/NunoCh.png
    - lib/assets/AswangCategory.png
    - lib/assets/EngkantoCategory.png
    - lib/assets/G&GCategory.png
    - lib/assets/GhostCategory.png
    - lib/assets/MiscCategory.png

  fonts:
    - family: BonaNova
      fonts:
        - asset: fonts/BonaNovaSC-Regular.ttf
    - family: InstrumentSans
      fonts:
        - asset: fonts/InstrumentSans-Regular.ttf
